# ProcessModule Backend Publish Script
# PowerShell betiği - Yönetici olarak çalıştırın

param(
    [string]$OutputPath = "C:\Publish\ProcessModuleAPI",
    [string]$Configuration = "Release"
)

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "ProcessModule Backend Publish Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Proje dizinine git
$ProjectPath = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ProjectPath

Write-Host "1. Cleaning previous build..." -ForegroundColor Yellow
if (Test-Path "$ProjectPath\ProcessModule.WebAPI\bin") {
    Remove-Item -Path "$ProjectPath\ProcessModule.WebAPI\bin" -Recurse -Force
}
if (Test-Path "$ProjectPath\ProcessModule.WebAPI\obj") {
    Remove-Item -Path "$ProjectPath\ProcessModule.WebAPI\obj" -Recurse -Force
}

Write-Host "2. Publishing backend to $OutputPath..." -ForegroundColor Yellow
dotnet publish "$ProjectPath\ProcessModule.WebAPI\ProcessModule.WebAPI.csproj" `
    -c $Configuration `
    -o $OutputPath `
    --self-contained false `
    -p:PublishReadyToRun=false

if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "✅ Backend published successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next Steps:" -ForegroundColor Cyan
    Write-Host "1. Update appsettings.json in $OutputPath" -ForegroundColor White
    Write-Host "2. Configure SQL Server connection string" -ForegroundColor White
    Write-Host "3. Run database migrations" -ForegroundColor White
    Write-Host "4. Create IIS site pointing to $OutputPath" -ForegroundColor White
    Write-Host ""
    Write-Host "Published files location: $OutputPath" -ForegroundColor Green
} else {
    Write-Host ""
    Write-Host "❌ Publish failed! Check errors above." -ForegroundColor Red
    exit 1
}

# web.config kontrolü
if (Test-Path "$OutputPath\web.config") {
    Write-Host "✅ web.config found (required for IIS)" -ForegroundColor Green
} else {
    Write-Host "⚠️  web.config not found! It will be auto-generated by IIS." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Press any key to continue..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
